language: python
sudo: false
branches:
only:
  - master

matrix:
  include:
    - python: 3.6
      env: PYSAL_PLUS=false MPLBACKEND="pdf"
    - python: 3.6
      env: PYSAL_PLUS=true MPLBACKEND="pdf"
    - python: 3.7
      dist: xenial
      sudo: true
      env: PYSAL_PLUS=false MPLBACKEND="pdf"
    - python: 3.7
      dist: xenial
      sudo: true
      env: PYSAL_PLUS=true MPLBACKEND="pdf"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes pip
  - pip install -r requirements.txt
  - pip install -r requirements_tests.txt
  - if "$PYSAL_PYPI"; then
        echo 'testing pypi libpysal' && pip install libpysal;
    else
        echo 'testing git libpysal';
        git clone https://github.com/pysal/libpysal.git; cd libpysal; pip install .; cd ../;
    fi;


script:
  - python setup.py sdist >/dev/null
  - python setup.py install
  - nosetests --verbose --with-coverage --cover-package=esda;

notifications:
    email:
        recipients:
            - levi.john.wolf+travis@gmail.com
            - sjsrey+travis@gmail.com
            - weikang9009@gmail.com
        on_success: change
        on_failure: change

after_success:
  - coveralls
